### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MateoConLechuga** [cardenaso11/GB2CE#1]
Most all of these parts are a part of Cesium, available here: https://github.com/MateoConLechuga/Cesium

It is licensed under the BDS 3 Clause, so I would much appreciate it if this could be added to the licensing info if you so desire. I don't really mind either way, but if you didn't write it, it is always a good idea to cite it. Thanks! :)

**Comment by ez80** [comment]
Mateo: I find it somewhat humorous that a new member came and brought your attention to this, and this caused you to "license" it. :)

**Comment by MateoConLechuga** [comment]
Cesium has always had the license since its initial commit. I don't really
mind about it, looks like you could use a bit of help. The eZ80 is a later
subset of the Z80, so emulation should be a bit easier :)

**Comment by cardenaso11** [comment]
@MateoConLechuga  Wheewee, I didn't really consider this as a serious project (seriously, if you take a look at my source code it's nothing but me just figuring out a way to store massive gameboy ROMs). But thank you for informing me, I'll update the license. Sorry if you felt like I was ripping off your work.

**Comment by MateoConLechuga** [comment]
Not at all! You can use it as you please, just was wondering if you would
like any help with it. I would recommend creating an account at cemetech.net
if you have any questions.

**Comment by cardenaso11** [comment]
I have an account, and I certainly will ask if I need anything. Thanks ^.^
